### PR TITLE
Enhancement/10

### PR DESCRIPTION
**Pull request by abaliunov-sc**
Fixed error "Rich Editor does not show cursor on UI in empty lines"

### CODE REVIEW

**Comment by kvolkovich-sc** [comment]
Bugs checklist for @abaliunov-sc :

---

- [ ] **How reproduce:** scroll to `code`, mouse click to next line (not so easy), write some text and press <kbd>Return</kbd>.

bug1

---

**Current behavior:** line break added, but cursor not jumps to next line
**Expected behavior:** line break added and cursor jumps to next line

- [ ] **How reproduce:** scroll to **Indented code** mouse click to end of code block,
 press<kbd>Return</kbd>.

bug2

**Current behavior:** new empty code block added
**Expected behavior:** old code block should increase in size

---

- [ ] **How reproduce:** scroll to **Lists** mouse click to end of one of first-level list item,
 press <kbd>Return</kbd>.

bug3

**Current behavior:** new child list item added with two bullets 
**Expected behavior:** new child list item added with one bullet

---

- [ ] **How reproduce:** scroll to **Definition lists** mouse click to end of **Term1** press <kbd>Return</kbd>, then press <kbd>Return</kbd> again.

bug4

**Current behavior:** new line added after **second** <kbd>Return</kbd> press
**Expected behavior:** new line added after **first** <kbd>Return</kbd> press

**Comment by abaliunov-sc** [comment]
First bug fixed.
Second bug is not related to serializer seems like behavior of Slate Editor. Should be reviewed by @ddivin-sc

**Comment by kvolkovich-sc** [comment]
**Bug**

**How reproduce:** in "plain editor mode" type a link inside bold / italic / strikethrough. Switch to "rich editor mode", click to some text, switch back to "plain editor mode".

bug5

**Current behavior:** Bold / italic / strikethrough symbols disappeared.
**Expected behavior:** Nothing disappeared.

**Comment by asergeev-sc** [comment]
The feature is not actual for the moment.

**Pull request closed without merging**
